#define CRAFTING_RESULT "craftresult"
#define CRAFTING_AMOUNT "craftamount"
#define CRAFTING_TIME "crafttime"
#define CRAFTING_ITEM "craftsource"
#define CRAFTING_SOUND "craftsound"
#define CRAFTING_SURFACE "craftsurface"
