#define NUKA_VENDOR_DROP_RARE list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_quantum = 3, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_custom = 1, /obj/item/reagent_containers/food/drinks/bottle/ms13/nukashine = 1, /obj/item/stack/ms13/currency/prewar/fifty = 0.5)
#define NUKA_VENDOR_DROP_HIGH list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cola = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_quantum = 2, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_quartz = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_wild = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_lime = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_custom = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_victory = 1, /obj/item/stack/ms13/currency/prewar/twenty = 0.5, /obj/item/stack/ms13/currency/prewar/fourty = 0.5)
#define NUKA_VENDOR_DROP_MEDIUM list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cola = 3, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_dark = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_victory = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cranberry = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cherry = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_grape = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_orange = 1, /obj/item/stack/ms13/currency/prewar/ten = 1)
#define NUKA_VENDOR_DROP_LOW list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cola = 6, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_cherry = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_grape = 1, /obj/item/reagent_containers/food/drinks/soda_cans/ms13/nuka_orange = 1, /obj/item/stack/sheet/ms13/glass = 0.5, /obj/item/stack/ms13/currency/prewar/five = 0.5)

#define SARSPA_VENDOR_DROP_RARE list(/obj/item/reagent_containers/food/drinks/bottle/ms13/whiskey = 2, /obj/item/stack/ms13/currency/prewar/fourty = 0.5)
#define SARSPA_VENDOR_DROP_HIGH list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/sarsaparilla = 1, /obj/item/reagent_containers/food/drinks/bottle/ms13/whiskey = 0.5, /obj/item/stack/ms13/currency/prewar/twenty = 0.5)
#define SARSPA_VENDOR_DROP_MEDIUM list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/sarsaparilla = 3, /obj/item/stack/ms13/currency/prewar/ten = 0.5)
#define SARSPA_VENDOR_DROP_LOW list(/obj/item/reagent_containers/food/drinks/soda_cans/ms13/sarsaparilla = 1, /obj/item/stack/ms13/currency/prewar/five = 0.5, /obj/item/stack/sheet/ms13/glass = 0.5)

#define CIGARETTE_VENDOR_DROP_RARE list(/obj/item/seeds/ms13/coyote = 1, /obj/item/food/grown/ms13/coyote = 1, /obj/item/ms13/dried/tobacco = 1, /obj/item/lighter/ms13/zippo = 1, /obj/item/reagent_containers/ms13/lighterfluid = 1, /obj/item/stack/ms13/currency/prewar/fourty = 0.5)
#define CIGARETTE_VENDOR_DROP_HIGH list(/obj/item/lighter/ms13/zippo = 1, /obj/item/storage/box/matches/ms13 = 2, /obj/item/storage/fancy/ms13/cigarettes/kools = 2, /obj/item/storage/fancy/ms13/cigarettes/luckystrike = 0.5, /obj/item/storage/fancy/ms13/cigarettes/luckystrike/random = 0.5, /obj/item/stack/ms13/currency/prewar/twenty = 1)
#define CIGARETTE_VENDOR_DROP_MEDIUM list(/obj/item/storage/fancy/ms13/cigarettes/winston = 1, /obj/item/storage/fancy/ms13/cigarettes/marlboro = 1, /obj/item/storage/fancy/ms13/cigarettes/salem = 1, /obj/item/ms13/rolling_paper = 1, /obj/item/stack/ms13/currency/prewar/ten = 0.5)
#define CIGARETTE_VENDOR_DROP_LOW list(/obj/item/storage/fancy/ms13/cigarettes/marlboro/random = 1, /obj/item/storage/fancy/ms13/cigarettes/kools/random = 1, /obj/item/storage/fancy/ms13/cigarettes/salem/random = 1, /obj/item/storage/fancy/ms13/cigarettes/winston/random = 1, /obj/item/ms13/cigarette/rollie = 1, /obj/item/ms13/cigarette = 1, /obj/item/stack/ms13/currency/prewar/five = 1)
